[env:teensy41]
platform  = teensy
board     = teensy41
framework = arduino

lib_deps =
    paulstoffregen/Encoder
    adafruit/Adafruit BNO055
    adafruit/Adafruit Unified Sensor

monitor_speed = 115200
